// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD05jM-zZwWVBP6g8-gdNHEjhOaxb6b71U',
    appId: '1:552626152643:web:aac67d931f17c37341ae76',
    messagingSenderId: '552626152643',
    projectId: 'reddit-clone-2a306',
    authDomain: 'reddit-clone-2a306.firebaseapp.com',
    storageBucket: 'reddit-clone-2a306.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0PPdSNJwfk26OTYnov8jNVljDVtvAdJM',
    appId: '1:552626152643:android:8ac1abf51bfc668141ae76',
    messagingSenderId: '552626152643',
    projectId: 'reddit-clone-2a306',
    storageBucket: 'reddit-clone-2a306.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzzRKxOjejNMR8n9USLNQ1E0UO_nMufXA',
    appId: '1:552626152643:ios:d1a7ee6b2e47929d41ae76',
    messagingSenderId: '552626152643',
    projectId: 'reddit-clone-2a306',
    storageBucket: 'reddit-clone-2a306.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
